
name: cppcheck

on:
  push:
  workflow_dispatch:
jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: sudo apt install -y cppcheck
      - name: run
        run: cppcheck --enable=all --error-exitcode=-1 ./ 1>/dev/null
